on: [push]
name: Tests

jobs:
  stack:
    name: stack
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1.4
      id: haskell
      with:
        enable-stack: true

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: |
            ${{ steps.haskell.outputs.cabal-store }}
            ~/.stack
            ~/.config/AdventOfCode
            .stack-work
        key: advent-v3-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('advent-solutions.cabal') }}-${{ hashFiles('lib/advent.cabal') }}
        restore-keys: |
            advent-v3-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('advent-solutions.cabal') }}-${{ hashFiles('lib/advent.cabal') }}
            advent-v3-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-
            advent-v3-${{ runner.os }}-

    - name: Build tests, lib, and exe
      run: stack build --test --no-run-tests

    - name: Prepare session token
      env:
        SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
      run: |
          mkdir -p ~/.config/AdventOfCode
          echo -n "$SESSION_TOKEN" > ~/.config/AdventOfCode/session-token.txt

    - name: Run tests
      run: stack test advent-solutions:test --verbosity warning

    - name: Create svg badges
      working-directory: "./.github"
      run: |
          mkdir svg
          stack run --verbosity silent -- badge gold   > svg/gold.svg
          stack run --verbosity silent -- badge silver > svg/silver.svg

    - name: Get short SHA
      id: scratch
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Save badges to Github Pages
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
          allow_empty_commit: true
          full_commit_message: ${{ steps.scratch.outputs.sha8 }} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.github/svg
          user_email: "actions@github"
          user_name: "Github Actions"
