on: [push]
name: Stack

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1.4
      id: haskell
      with:
        enable-stack: true

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: |
            ${{ steps.haskell.outputs.cabal-store }}
            ~/.stack
            .stack-work
        key: ${{ runner.os }}-stack-cache-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('package.yaml') }}
        restore-keys: |
            ${{ runner.os }}-stack-cache-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('package.yaml') }}
            ${{ runner.os }}-stack-cache-${{ hashFiles('stack.yaml.lock') }}-
            ${{ runner.os }}-stack-

    - name: Build tests, lib, and exe
      run: stack build Advent:{test,exe} --no-run-tests

    - name: Prepare session token
      env:
        SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
      run: |
          mkdir -p ~/.config/AdventOfCode
          echo -n "$SESSION_TOKEN" > ~/.config/AdventOfCode/session-token.txt

    - name: Run tests
      run: stack test --verbosity warning
